#Q1 Mean and Variance.

In [1]:
import numpy as np

def compute_mean(array):
    return np.mean(array)

def compute_variance(array, sample=True):
    if sample:
        return np.var(array, ddof=1)
    else:
        return np.var(array)

def main():
    sample_vector = np.array([float(input(f"Enter element {i+1}: ")) for i in range(int(input("Enter the dimension of the vector: ")))])

    print("Sample Vector:", sample_vector)
    mean = compute_mean(sample_vector)
    sample_variance = compute_variance(sample_vector)
    population_variance = compute_variance(sample_vector, sample=False)

    print("Mean:", mean)
    print("Sample Variance:", sample_variance)
    print("Population Variance:", population_variance)

if __name__ == "__main__":
    main()

Enter the dimension of the vector: 3
Enter element 1: 2
Enter element 2: 3
Enter element 3: 4
Sample Vector: [2. 3. 4.]
Mean: 3.0
Sample Variance: 1.0
Population Variance: 0.6666666666666666


#Q2 Covariance between two vectors.

In [2]:
### cov(X, Y) = Σ((Xi - X̄) * (Yi - Ȳ)) / n-1
import numpy as np

def compute_covariance(vector1, vector2):
    covariance = np.sum((vector1 - np.mean(vector1)) * (vector2 - np.mean(vector2))) / (len(vector1) - 1)
    return covariance

def main():
    M = int(input("Enter the dimension of vector 1: "))
    N = int(input("Enter the dimension of vector 2: "))

    vector1 = np.array(input(f"Enter {M} elements for vector 1 : ").split(), dtype=float)
    vector2 = np.array(input(f"Enter {N} elements for vector 2 : ").split(), dtype=float)

    covariance = compute_covariance(vector1, vector2)

    print("Covariance between Vector 1 and Vector 2:", covariance)

if __name__ == "__main__":
    main()

Enter the dimension of vector 1: 3
Enter the dimension of vector 2: 3
Enter 3 elements for vector 1 : 5 11 6
Enter 3 elements for vector 2 : 4 6 16
Covariance between Vector 1 and Vector 2: -4.333333333333334


#Q3 Correlation between two vectors.

In [1]:
import numpy as np

def compute_correlation(vector1, vector2):
    covariance = np.cov(vector1, vector2)[0][1]
    correlation = covariance / (np.std(vector1) * np.std(vector2))
    return correlation

def main():
    N = int(input("Enter the dimension of the vectors: "))

    vector1 = np.array(input(f"Enter {N} elements for vector 1 : ").split(), dtype=float)
    vector2 = np.array(input(f"Enter {N} elements for vector 2 : ").split(), dtype=float)

    if len(vector1) != N or len(vector2) != N:
        print(f"Error: Vectors must be of length {N}.")
        return

    correlation = compute_correlation(vector1, vector2)

    print("Correlation between Vector 1 and Vector 2:", correlation)

if __name__ == "__main__":
    main()

Enter the dimension of the vectors: 3
Enter 3 elements for vector 1 : 5 6 2 
Enter 3 elements for vector 2 : 6 7 3
Correlation between Vector 1 and Vector 2: 1.5


#Q4 Covariance matrix and Correlation matrix.

In [2]:
def calculate_covariance_matrix(data):
    mean = np.mean(data, axis=0)
    centered_data = data - mean
    covariance_matrix = np.cov(centered_data.T, bias=False)
    return covariance_matrix

def calculate_correlation_matrix(data):
    covariance_matrix = calculate_covariance_matrix(data)
    std_dev = np.std(data, axis=0)
    correlation_matrix = np.divide(covariance_matrix, np.outer(std_dev, std_dev), where=(std_dev[:, None] * std_dev[None, :]) != 0)
    return correlation_matrix

rows = int(input("Enter the number of rows (samples): "))
cols = int(input("Enter the number of columns (features): "))

data = np.zeros((rows, cols))

print("Enter the data:")
for i in range(rows):
    data[i] = [float(val) for val in input(f"Enter values for sample {i+1}: ").split()]

covariance_matrix = calculate_covariance_matrix(data)
correlation_matrix = calculate_correlation_matrix(data)

print("Covariance Matrix:\n", covariance_matrix)
print("Correlation Matrix:\n", correlation_matrix)

Enter the number of rows (samples): 3
Enter the number of columns (features): 3
Enter the data:
Enter values for sample 1: 5 6 2
Enter values for sample 2: 6 7 3
Enter values for sample 3: 5 11 6
Covariance Matrix:
 [[ 0.33333333 -0.5        -0.33333333]
 [-0.5         7.          5.5       ]
 [-0.33333333  5.5         4.33333333]]
Correlation Matrix:
 [[ 1.5        -0.49099025 -0.41602515]
 [-0.49099025  1.5         1.49793814]
 [-0.41602515  1.49793814  1.5       ]]
